#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"


$L "____ _    ____ _  _ _ _  _ ____    _  _ ____ _  _ _  _ ____ _   _ ";
$L "|___ |    |__| |\\/| | |\\ | | __    |\\/| |  | |\\ | |_/  |___  \\_/  ";
$L "|    |___ |  | |  | | | \\| |__]    |  | |__| | \\| | \\_ |___   |   ";
$L "Welcome to `getprop ro.build.display.id` - Android `getprop ro.build.version.release`";
